### ISSUE TITLE
Return Url Problems

### ISSUE THREAD

**Issue by lemusi** [mmabingo/WC_CyberSourceSecureAcceptance_SOP#1]
Hi. First of all. Thank you for this contribution! If I can help in any way let me know.

Just I don't have a clue on how to fix the return URL because the one you provided on the instructions didn't work.. I get a 404 error from the website.

Just to be clear.. This is the URL we are supposed to configure on Cybersource response option.

Any ideas?

Thanks!

**Comment by mmabingo** [comment]
Hello. Thanks for reporting this issue, it was a typo in the read me file of which I have corrected now.

The correct URL is https://www.example.com/?wc-api=wc_gateway_cybersource_secure_acceptance_sop_response

You are right, this is the url you will need to update in CyberSource Business Center.

Regards.

**Comment by lemusi** [comment]
yep! That's the one! Thanks for the quick response!
